PlayIT/PlayIT/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from appPlayIT.views import *
from appPlayIT.forms import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'PlayIT.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^api/', include('playItAPI.urls', namespace='playItAPI')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    url(r'^$', mainpage, name='home'),
    url(r'^browse$', browse),
    url(r'^track/$', track_list),
    url(r'^track.json/$', track_list_json),
    url(r'^track.xml/$', track_list_xml),
    url(r'^track/(\w+)/$', track),
    url(r'^pub/$', get_pub_list),
    url(r'^pub.json/$', get_pub_list_json),
    url(r'^pub.xml/$', get_pub_list_xml),
    url(r'^pub/(\d+)/$', get_pub),
    url(r'^pub/(?P<pk>\d+)/edit/$', LoginRequiredCheckIsOwnerUpdateView.as_view(model=Pub, form_class=PubForm), name='pub_edit'),
    url(r'^pub/(?P<pk>\d+)/delete/$', LoginRequiredCheckIsOwnerDeleteView.as_view(model=Pub), name='pub_delete'),
    url(r'^pub/create/$', PubCreate.as_view(), name='pub_create'),
    url(r'^pub/(?P<pk>\d+)/playlist/create/$', PlaylistCreate.as_view(), name='playlist_create'),
    url(r'^pub/(?P<pk>\d+)/review/create/$', 'appPlayIT.views.review', name='review_create'),
    url(r'^pub/(?P<pkr>\d+)/review/(?P<pk>\d+)/edit/$', LoginRequiredCheckIsOwnerUpdateView.as_view(model=Review, form_class=ReviewForm), name='review_edit'),
    url(r'^pub/(?P<pkr>\d+)/review/(?P<pk>\d+)/delete/$', LoginRequiredCheckIsOwnerDeleteView.as_view(model=Review), name='review_delete'),
    url(r'^pub/(?P<pkr>\d+)/playlist/(?P<pk>\d+)/edit/$', LoginRequiredCheckIsOwnerUpdateView.as_view(model=Playlist, form_class=PlaylistForm), name='playlist_edit'),
    url(r'^pub/(?P<pkr>\d+)/playlist/(?P<pk>\d+)/delete/$', LoginRequiredCheckIsOwnerDeleteView.as_view(model=Playlist), name='playlist_delete'),
    url(r'^pub/(\d+)/playlist/(?P<pkr>\d+)/add_track/(?P<pk>\w+)/$', 'appPlayIT.views.add_track_to_playlist', name='add_track_to_playlist'),
    url(r'^pub/(\d+)/playlist/(?P<pkr>\d+)/remove_track/(?P<pk>\w+)/$', 'appPlayIT.views.remove_track_from_playlist', name='remove_track_from_playlist'),
    url(r'^follow_pub/(?P<pk>\d+)/$', 'appPlayIT.views.follow_pub', name='follow_pub'),
    url(r'^unfollow_pub/(?P<pk>\d+)/$', 'appPlayIT.views.unfollow_pub', name='unfollow_pub'),
    url(r'^pub/(\d+).xml/$', get_pub_xml),
    url(r'^pub/(\d+).json/$', get_pub_json),
    url(r'^pub/(\d+)/playlist.json/$', get_pub_playlists_json),
    url(r'^pub/(\d+)/playlist.xml/$', get_pub_playlists_xml),
    url(r'^playlist/$', get_playlist_list),
    url(r'^playlist.json/$', get_playlist_list_json),
    url(r'^playlist.xml/$', get_playlist_list_xml),
    url(r'^playlist/(\w+)/$', get_playlist),
    url(r'^playlist/(\w+).json/$', get_playlist_json),
    url(r'^playlist/(\w+).xml/$', get_playlist_xml),
    url(r'^playlist/(\w+)/track.json/$', get_playlist_tracks_json),
    url(r'^playlist/(\w+)/track.xml/$', get_playlist_tracks_xml)
)

PlayIT/appPlayIT/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

class Pub(models.Model):
    name = models.TextField()
    street = models.TextField()
    number = models.IntegerField()
    city = models.TextField()
    zipCode = models.TextField(blank=True, null=True)
    stateOrProvince = models.TextField(blank=True, null=True)
    country = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
        return "/pub/" + str(self.pk)

class User_Pub(models.Model):
    user = models.ForeignKey(User)
    pub = models.ForeignKey(Pub)
    class Meta:
        unique_together = ('user', 'pub')
    def __unicode__(self):
        return self.user.username + " - " +  self.pub.name

class Playlist(models.Model):
    pub = models.ForeignKey(Pub, related_name='playlists')
    name = models.TextField()
    user = models.ForeignKey(User, default=1)
    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
        return "/playlist/" + str(self.pk)

class Track(models.Model):
    spotify_id = models.TextField(primary_key=True)
    name = models.TextField()
    artist = models.TextField()
    #spotify_artist_id = models.TextField()
    album = models.TextField()
    #spotify_album_id = models.TextField()
    def __unicode__(self):
        return self.name + " - " + self.artist

class Playlist_Track(models.Model):
    playlist = models.ForeignKey(Playlist)
    track = models.ForeignKey(Track)
    user = models.ForeignKey(User)
    class Meta:
        unique_together = ('playlist', 'track')
    def __unicode__(self):
        return self.playlist.name + " - " +  self.track.name

class Review(models.Model):
    RATING_CHOICES = ((1,'1'),(2,'2'),(3,'3'),(4,'4'),(5,'5'))
    rating = models.PositiveSmallIntegerField('Ratings (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)
    pub = models.ForeignKey(Pub)
    def __unicode__(self):
        return self.pub.name + " - " + str(self.rating)
    def get_absolute_url(self):
        return "/pub/" + str(self.pub.pk)

PlayIT/appPlayIT/forms.py
from django.forms import ModelForm
from appPlayIT.models import Pub, Playlist, Track, Review

class PubForm(ModelForm):
    class Meta:
        model = Pub
        exclude = ('user',)

class PlaylistForm(ModelForm):
    class Meta:
        model = Playlist
        exclude = ('pub', 'user')

class TrackForm(ModelForm):
    class Meta:
        model = Track
        #exclude = ()

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        exclude = ('user', 'date', 'pub')

PlayIT/appPlayIT/views.py
from django.shortcuts import render, render_to_response
from SpotifyAPI.spotify import SpotifyBrowser
from django.contrib.auth.models import User
from appPlayIT.models import *
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from appPlayIT.forms import *
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from django.template import RequestContext

# Create your views here.
def mainpage(request):
    pubs = None
    if request.user.is_authenticated():
        pubs = Pub.objects.filter(user_pub__in=User_Pub.objects.filter(user=request.user))
    return render_to_response(
        'mainpage.html',
        {
                'user': request.user,
                'pubs' : pubs
        })

def browse_track(request, keyword, offset, limit, next_page, previous_page):
    return render_to_response(
        'browse_track.html',
        {
            'user': request.user,
            'keyword' : keyword,
            'tracks' : SpotifyBrowser.search_track(keyword, offset, limit)["tracks"],
            'next_page' : next_page,
            'previous_page': previous_page
        }
    )

def browse_artist(request, keyword, offset, limit, next_page, previous_page):
    return render_to_response(
        'browse_artist.html',
        {
            'user': request.user,
            'keyword' : keyword,
            'artists' : SpotifyBrowser.search_artist(keyword, offset, limit)["artists"],
            'next_page' : next_page,
            'previous_page' : previous_page
        }
    )

def browse_album(request, keyword, offset, limit, next_page, previous_page):
    return render_to_response(
        'browse_album.html',
        {
            'user': request.user,
            'keyword' : keyword,
            'albums' : SpotifyBrowser.search_album(keyword, offset, limit)["albums"],
            'next_page' : next_page,
            'previous_page' : previous_page
        }
    )

def browse_playlist(request, keyword, offset, limit, next_page, previous_page):
    return render_to_response(
        'browse_playlist.html',
        {
            'user': request.user,
            'keyword' : keyword,
            'playlists' : SpotifyBrowser.search_playlist(keyword, offset, limit)["playlists"],
            'next_page' : next_page,
            'previous_page' : previous_page
        }
    )

def browse(request):
    type = request.GET.get('type')
    keyword = request.GET.get('keyword')
    offset = int(request.GET.get('offset', 0))
    limit = int(request.GET.get('limit', 50))
    if not type or not keyword:
        return render_to_response(
            'browse.html',
            {
                    'user': request.user,
            })
    else:
        next_page = "/browse?keyword=" + keyword + "&type=" + type + "&limit=" + str(limit) + "&offset=" + str(offset+limit)
        previous_page = "/browse?keyword=" + keyword + "&type=" + type + "&limit=" + str(limit) + "&offset=" + str(offset-limit)
        if type == 'track':
            return browse_track(request, keyword, offset, limit, next_page, previous_page)
        elif type == 'artist':
            return browse_artist(request, keyword, offset, limit, next_page, previous_page)
        elif type == 'album':
            return browse_album(request, keyword, offset, limit, next_page, previous_page)
        elif type == 'playlist':
            return browse_playlist(request, keyword, offset, limit, next_page, previous_page)

def render_json_response(objects):
    json_data = serializers.serialize(u"json", objects)
    return HttpResponse(json_data, content_type=u"application/json")

def render_xml_response(objects):
    json_data = serializers.serialize(u"xml", objects)
    return HttpResponse(json_data, content_type=u"application/xml")

def track_list_json(request):
    return track_list(request, 'json')

def track_list_xml(request):
    return track_list(request, 'xml')

def track_list(request, format='html'):
    tracks = Track.objects.all()
    if format == 'xml':
        return render_xml_response(tracks)
    elif format == 'json':
        return render_json_response(tracks)
    else:
        return render_to_response(
            'track_list.html',
            {
                'user': request.user,
                'tracks' : tracks
            }
        )

def track(request, track_id):
    pubs = None
    pub_playlists = []
    if request.user.is_authenticated:
        pubs = Pub.objects.filter(user_pub__in=User_Pub.objects.filter(user=request.user))
        for pub in pubs:
            playlists = Playlist.objects.filter(pub = pub.id)
            if len(playlists) > 0:
                pub_playlists.append((pub, playlists))
    return render_to_response(
        'track.html',
        {
            'user' : request.user,
            'pubs' : pubs,
            'pub_playlists': pub_playlists,
            'track' : SpotifyBrowser.get_track_by_id(track_id)
        }
    )

def get_pub_list_json(request):
    return get_pub_list(request, 'json')

def get_pub_list_xml(request):
    return get_pub_list(request, 'xml')

def get_pub_list(request, format='html'):
    pubs = Pub.objects.all()
    if format == 'json':
        return render_json_response(pubs)
    elif format == 'xml':
        return render_xml_response(pubs)
    else:
        return render_to_response(
            'pub_list.html',
            {
                'user': request.user,
                'pubs' : pubs
            }
        )

def get_pub_json(request, pub_id):
    return get_pub(request, pub_id, 'json')

def get_pub_xml(request, pub_id):
    return get_pub(request, pub_id, 'xml')

def get_pub(request, pub_id, format='html'):
    try:
        pub = Pub.objects.get(id=pub_id)
    except:
        raise Http404('Pub not found.')
    if format == 'json':
        return render_json_response([pub,])
    elif format == 'xml':
        return render_xml_response([pub,])
    else:
        user_follow_pub = 0 # User not authenticated
        user_is_owner = False
        if request.user.is_authenticated():
            if pub.user == request.user:
                user_is_owner = True
            try:
                user_pub = User_Pub.objects.get(user = request.user, pub = pub)
                user_follow_pub = 1 # User follow pub
            except:
                user_follow_pub = 2 # User authenticated, user don't follow pub
        reviews = Review.objects.filter(pub=pub_id)
        reviews_avg = None
        if reviews:
            reviews_avg = sum([int(rating[0]) for rating in reviews.values_list('rating')])/float(len(reviews))
        print reviews_avg
        return render_to_response(
            'pub.html',
            {
                'user': request.user,
                'pub' : pub,
                'user_follow_pub': user_follow_pub,
                'user_is_owner': user_is_owner,
                'playlists' : Playlist.objects.filter(pub=pub_id),
                'RATING_CHOICES' : Review.RATING_CHOICES,
                'reviews' : reviews,
                'reviews_avg' : reviews_avg,
                'number_of_reviews' : len(reviews)
            }, RequestContext(request)
        )

def get_pub_playlists_json(request, pub_id):
    return get_pub_playlists(request, pub_id, 'json')

def get_pub_playlists_xml(request, pub_id):
    return get_pub_playlists(request, pub_id, 'xml')

def get_pub_playlists(requests, pub_id, format='html'):
    try:
        pub = Pub.objects.get(id=pub_id)
        playlists = Playlist.objects.filter(pub=pub_id)
    except:
        raise Http404('Pub not found.')
    if format == 'json':
        return render_json_response(playlists)
    elif format == 'xml':
        return render_xml_response(playlists)

def get_playlist_list_json(request):
    return get_playlist_list(request, 'json')

def get_playlist_list_xml(request):
    return get_playlist_list(request, 'xml')

def get_playlist_list(request, format='html'):
    playlists = Playlist.objects.all()
    if format == 'json':
        return render_json_response(playlists)
    elif format == 'xml':
        return render_xml_response(playlists)
    else:
        return render_to_response(
            'playlist_list.html',
            {
                'user': request.user,
                'playlists' : playlists
            }
        )

def get_playlist_json(request, playlist_id):
    return get_playlist(request, playlist_id, 'json')

def get_playlist_xml(request, playlist_id):
    return get_playlist(request, playlist_id, 'xml')

def get_playlist(request, playlist_id, format='html'):
    try:
        playlist = Playlist.objects.get(id=playlist_id)
    except:
        raise Http404('Playlist not found.')
    if format == 'json':
        return render_json_response([playlist,])
    elif format == 'xml':
        return render_xml_response([playlist,])
    else:
        user_is_owner = False
        if request.user.is_authenticated():
            if playlist.user == request.user:
                user_is_owner = True
        return render_to_response(
            'playlist.html',
            {
                'user': request.user,
                'playlist' : playlist,
                'tracks' : Track.objects.filter(playlist_track__in=Playlist_Track.objects.filter(playlist=playlist_id)),
                'pub' : playlist.pub,
                'user_is_owner': user_is_owner
            }
        )

def get_playlist_tracks(request, playlist_id, format='html'):
    try:
        playlist = Playlist.objects.get(id=playlist_id)
        tracks = Track.objects.filter(playlist_track__in=Playlist_Track.objects.filter(playlist=playlist_id))
    except:
        raise Http404('Playlist not found.')
    if format == 'json':
        return render_json_response(tracks)

PlayIT/appPlayIT/templates/basepage.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static "style/base.css" %}" />
    <title>{% block title %}PlayIt{% endblock %}</title>
</head>

<body>

<div id="header">
    {% block header %}
        {% if user.username %}
            <p>User {{ user.username }} (<a href="/accounts/logout/?next=/">logout</a>)</p>
        {% else %}
            <p><a href="/accounts/login/?next=/">Sign in</a></p>
        {% endif %}
    {% endblock %}
</div>


<div id="sidebar">
    {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/browse">Add track to pub playlist</a></li>
            <li><a href="/pub">Pubs</a></li>
            <li><a href="/pub/create">Create a pub</a></li>
            <li><a href="/playlist">Playlists</a></li>
        </ul>
    {% endblock %}
</div>

<div id="content">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>

<div id="footer">
    {% block footer %}{% endblock %}
</div>

</body>
</html>

PlayIT/appPlayIT/templates/browse.html
{% extends "basepage.html" %}
{% load staticfiles %}
{% block title %}PlayIT - Browse{% endblock %}
{% block content %}
    <h1>Search on Spotify</h1>
    <form method="get" action="/browse">
        <input type="search" name="keyword" />
        <select name="type">
            <option value="track">Track</option>
            <option value="artist">Artist</option>
            <option value="album">Album</option>
            <option value="playlist">Playlist</option>
        <input type="submit" value="Search"/>
    </form>
    {% block results %}
	{% endblock %}
{% endblock %}

PlayIT/appPlayIT/templates/browse_album.html
{% extends "browse.html" %}
{% block title %}PlayIT - {{ keyword }}{% endblock %}
{% block results %}
    <h2>Albums containing: {{ keyword }}</h2>
    <table style="width:100%" >
        <tr>
            <th>Name</th>
            <th>id</th>
        </tr>
        {% for album in albums.items %}
            <tr>
                <td>{{ album.name }}</td>
                <td>{{ album.id }}</td>
            </tr>
        {% endfor %}
    </table>
    <h3>Total results: {{ albums.total }}. Max displayed: {{ albums.limit }}. Offset: {{ albums.offset }}</h3>
    <p></p>
    {% if albums.previous %}
        <a href="{{ previous_page }}"><button>Previous page</button></a>
    {% endif %}
    {% if albums.next %}
        <a href="{{ next_page }}"><button>Next page</button></a>
    {% endif %}
{% endblock %}

PlayIT/appPlayIT/templates/browse_playlist.html
{% extends "browse.html" %}
{% block results %}
    <h2>Playlists containing: {{ keyword }}</h2>
    <table style="width:100%" >
        <tr>
            <th>Name</th>
            <th>id</th>
            <th>Owner</th>
        </tr>
        {% for playlist in playlists.items %}
            <tr>
                <td>{{ playlist.name }}</td>
                <td>{{ playlist.id }}</td>
                <td>{{ playlist.owner.id }}</td>
            </tr>
        {% endfor %}
    </table>
    <h3>Total results: {{ playlists.total }}. Max displayed: {{ playlists.limit }}. Offset: {{ playlists.offset }}</h3>
    <p></p>
    {% if playlists.previous %}
        <a href="{{ previous_page }}"><button>Previous page</button></a>
    {% endif %}
    {% if playlists.next %}
        <a href="{{ next_page }}"><button>Next page</button></a>
    {% endif %}
{% endblock %}

PlayIT/appPlayIT/templates/browse_track.html
{% extends "browse.html" %}
{% block title %}PlayIT - {{ keyword }}{% endblock %}
{% block results %}
    <h2>Tracks containing: {{ keyword }}</h2>
    <table style="width:100%" >
        <tr>
            <th>Name</th>
            <th>Artist</th>
            <th>Album</th>
            <th>id</th>
        </tr>
        {% for track in tracks.items %}
            <tr>
                <td>{{ track.name }}</td>
                <td>{{ track.artists.0.name }}</td>
                <td>{{ track.album.name }}</td>
                <td>{{ track.id }}</td>
                <td><a href="/track/{{ track.id }}">Add to playlist</a></td>
            </tr>
        {% endfor %}
    </table>
    <h3>Total results: {{ tracks.total }}. Max displayed: {{ tracks.limit }}. Offset: {{ tracks.offset }}</h3>
    <p></p>
    {% if tracks.previous %}
        <a href="{{ previous_page }}"><button>Previous page</button></a>
    {% endif %}
    {% if tracks.next %}
        <a href="{{ next_page }}"><button>Next page</button></a>
    {% endif %}
{% endblock %}

PlayIT/appPlayIT/templates/delete_form.html
{% extends "basepage.html" %}
{% block content %}
    <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input type="submit" value="Delete" />
    </form>
{% endblock %}

PlayIT/appPlayIT/templates/form.html
{% extends "basepage.html" %}
{% load staticfiles %}
{% block content %}

    <script>
        $(function() {
            $.getJSON("{% static "countries.json" %}", {}, function (countries) {
                $("#id_country").autocomplete({
                    source: countries
                });
            });
            $("#id_city").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term,
                            username: "demo"
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    stateOrProvince: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    if (ui.item) {
                        $("#id_stateOrProvince").val(ui.item.stateOrProvince);
                        $("#id_country").val(ui.item.countryName);
                        $("#id_zipCode").val("");
                    }
                }
            });
        });
    </script>

    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <p></p>
        <input type="submit" value="Send"/>
    </form>
{% endblock %}

PlayIT/appPlayIT/templates/mainpage.html
{% extends "basepage.html" %}
{% block title %}PlayIT - Home{% endblock %}
{% block content %}
    {% if user.username %}
        {% if pubs %}
            <h1>List of user pubs</h1>
            <ul>
                {% for pub in pubs %}
                    <li><h2><a href="/pub/{{ pub.id }}">{{ pub.name }}</a></h2></li>
                    <h3>{{ pub.street }}, {{ pub.number }} - {{ pub.city }}</h3>
                {% endfor %}
            </ul>
       {% else %}
            <h2>This user has no registered pubs</h2>
       {% endif %}
    {% else %}
        <h2><a href="/accounts/login/">Login</a> to access your registered pubs</h2>
    {% endif %}
{% endblock %}

PlayIT/appPlayIT/templates/playlist.html
{% extends "basepage.html" %}
{% load staticfiles %}
{% block title %}PlayIT - {{ pub.name }} - {{ playlist.name }}{% endblock %}
{% block footer %}Created by {{ playlist.user }}{% endblock %}
{% block content %}
    <h1>{{ pub.name }} - {{ playlist.name }}
    {% if user_is_owner %}
        <a href="/pub/{{ pub.id }}/playlist/{{ playlist.id }}/edit"> (edit)</a>
        <a href="/pub/{{ pub.id }}/playlist/{{ playlist.id }}/delete"> (remove)</a>
    {% endif %}</h1>
    <h2>Playlist of pub: <a href="/pub/{{ pub.id }}">{{ pub.name }}</a></h2>
    {% if tracks %}
        <h2>Showing tracks:</h2>
        <table style="width:100%" >
            <tr>
                <th>Name</th>
                <th>Artist</th>
                <th>Album</th>
            </tr>
            {% for track in tracks %}
                <tr>
                    <td>{{ track.name }}</td>
                    <td>{{ track.artist }}</td>
                    <td>{{ track.album }}</td>
                    {% if user_is_owner %}
                        <td><a href="/pub/{{ pub.id }}/playlist/{{ playlist.id }}/remove_track/{{ track.spotify_id }}">Remove track</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h3>This playlist is empty!</h3>
    {% endif %}
{% endblock %}

PlayIT/appPlayIT/templates/playlist_list.html
{% extends "basepage.html" %}
{% block title %}PlayIT - Playlists{% endblock %}
{% block content %}
    <h1>Playlists</h1>
    {% if playlists %}
            <ul>
                {% for playlist in playlists %}
                    <li><h2><a href="/playlist/{{ playlist.id }}">{{ playlist.name }}</a></h2></li>
                {% endfor %}
            </ul>
    {% else %}
        <h2>There are no registered playlists!</h2>
    {% endif %}
{% endblock %}

PlayIT/appPlayIT/templates/pub_list.html
{% extends "basepage.html" %}
{% block title %}PlayIT - Pubs{% endblock %}
{% block content %}
    <h1>Pubs</h1>
    {% if pubs %}
        <ul>
            {% for pub in pubs %}
                <li><h2><a href="/pub/{{ pub.id }}">{{ pub.name }}</a></h2></li>
                    <h3>{{ pub.street }}, {{ pub.number }} - {{ pub.city }}</h3>
            {% endfor %}
        </ul>
    {% else %}
        <h2>There are no registered pubs!</h2>
    {% endif %}
{% endblock %}

PlayIT/appPlayIT/templates/track.html
{% extends "basepage.html" %}
{% block title %}PlayIT - {{ track.name }}{% endblock %}
{% block content %}
    <h1>{{ track.name }} - {{ track.artists.0.name }}</h1>
    <h3>Album: {{ track.album.name }}</h3>
    <h3>Id track Spotify: {{ track.id }}</h3>
    {% if user.username %}
        {% if pub_playlists %}
            <h2>List of user pubs:</h2>
                {% for pub_playlist in pub_playlists %}
                    {% with pub=pub_playlist.0 %}
                    <h3>{{ pub.name }}</h3>
                    <ul>
                        {% for playlist in pub_playlist.1 %}
                            <li><a href="/playlist/{{ playlist.id }}">{{ playlist.name }}</a>
                            <a href="/pub/{{ pub.id }}/playlist/{{ playlist.id }}/add_track/{{ track.id }}"><button>Add song to this playlist</button></a></li>
                        {% endfor %}
                    </ul>
                    {% endwith %}
                {% endfor %}
           {% else %}
                <h2>Your registered pubs has no playlists!</h2>
           {% endif %}
    {% endif %}
    {% block results %}
	{% endblock %}
{% endblock %}

PlayIT/appPlayIT/templates/track_list.html
{% extends "basepage.html" %}
{% block title %}PlayIT - Tracks{% endblock %}
{% block content %}
    <h1>Tracks</h1>
    {% if tracks %}
        <table style="width:100%" >
            <tr>
                <th>Name</th>
                <th>Artist</th>
                <th>Album</th>
                <th>id</th>
            </tr>
            {% for track in tracks %}
                <tr>
                    <td>{{ track.name }}</td>
                    <td>{{ track.artist }}</td>
                    <td>{{ track.album }}</td>
                    <td>{{ track.spotify_id }}</td>
                    <td><a href="/track/{{ track.spotify_id }}">Add to playlist</a></td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>There are no registered tracks!</h2>
    {% endif %}
{% endblock %}